package db.prob.datalog.query.Absyn; // Java Package generated by the BNF Converter.

import db.prob.datalog.query.Components.Attribute;
import db.prob.datalog.query.Visitable;
import db.prob.datalog.query.Visitor;

import java.util.List;

public class Head  implements Visitable
{
  public PredicateSym predicatesym_;
  public List<Attribute> listterm_;

  public Head(PredicateSym p1, List<Attribute> p2) { predicatesym_ = p1; listterm_ = p2; }

  public void accept(Visitor v) { v.visit(this); }
}

