package db.prob.datalog.query.Absyn; // Java Package generated by the BNF Converter.

import db.prob.datalog.query.Visitable;
import db.prob.datalog.query.Visitor;

public class LiteralNE extends Literal
{
  public Term term_1, term_2;

  public LiteralNE(Term p1, Term p2) { term_1 = p1; term_2 = p2; }

  public void accept(Visitor v) { v.visit(this); }
}

