package db.prob.datalog.query.Absyn; // Java Package generated by the BNF Converter.

import db.prob.datalog.query.Visitable;
import db.prob.datalog.query.Visitor;

public class TermVar extends Term
{
  public Variable variable_;

  public TermVar(Variable p1) { variable_ = p1; }

  public void accept(Visitor v) { v.visit(this); }
}

