package db.prob.datalog.query.Absyn.operators; // Java Package generated by the BNF Converter.

import db.prob.datalog.query.Absyn.Schema.RelationAttribute;

import java.util.Set;

public interface Literal {
    public Set<RelationAttribute> get_attr();

}
