package db.prob.datalog.query.Absyn.operators; // Java Package generated by the BNF Converter.

import db.prob.datalog.query.Absyn.Schema.RelationAttribute;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

public class QueryJoin implements Literal {
    public RelationAttribute term_left_, term_right_;
    private Set<RelationAttribute> terms = new HashSet<RelationAttribute>();

    public QueryJoin(RelationAttribute term_left, RelationAttribute term_right) {
        term_left_ = term_left;
        term_right_ = term_right;
        terms.add(term_left);
        terms.add(term_right);
    }

    @Override
    public Set<RelationAttribute> get_attr() {
        return Collections.emptySet();
    }

    public Set<RelationAttribute> get_terms() {
        return this.terms;
    }
}