package db.prob.datalog.query.Absyn.operators; // Java Package generated by the BNF Converter.

import db.prob.datalog.query.Absyn.Schema.RelationAttribute;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/**
 * Literal item of the form R1.a = R2.b
 */
public class QueryJoin implements Literal {
    public RelationAttribute termLeft, termRight;
    private Set<RelationAttribute> terms = new HashSet<RelationAttribute>();

    public QueryJoin(RelationAttribute term_left, RelationAttribute term_right) {
        termLeft = term_left;
        termRight = term_right;
        terms.add(term_left);
        terms.add(term_right);
    }

    /**
     * No attributes are referenced in join
     *
     * @return
     */
    @Override
    public Set<RelationAttribute> getAttributes() {
        return Collections.emptySet();
    }

    public Set<RelationAttribute> getTerms() {
        return this.terms;
    }

    public String toString() {
        return "Join on " + this.termLeft + "=" + this.termRight;
    }
}