package db.prob.datalog.query.Absyn; // Java Package generated by the BNF Converter.

import db.prob.datalog.query.Visitable;
import db.prob.datalog.query.Visitor;

import java.util.List;

public class Body  implements Visitable
{
  public List<Literal> listliteral_;

  public Body(List<Literal> p1) { listliteral_ = p1; }

  public void accept(Visitor v) {
      v.visit(this);
  }
}

