package db.prob.datalog.query.Absyn; // Java Package generated by the BNF Converter.

import db.prob.datalog.query.Visitable;
import db.prob.datalog.query.Visitor;

public class ConstantId extends Constant implements Visitable
{
  public String ident_;

  public ConstantId(String p1) { ident_ = p1; }

  public void accept(Visitor v) { v.visit(this); }
}

