package db.prob.datalog.query.Absyn; // Java Package generated by the BNF Converter.

import db.prob.datalog.query.Visitable;
import db.prob.datalog.query.Visitor;

import java.util.List;

public class LiteralTerms extends Literal
{
  public PredicateSym predicatesym_;
  public List<Term> listterm_;

  public LiteralTerms(PredicateSym p1, List<Term> p2) { predicatesym_ = p1; listterm_ = p2; }

  public void accept(Visitor v) {
      v.visit(this);
  }
}

