package db.prob.datalog.query.Absyn; // Java Package generated by the BNF Converter.

import java.util.Collections;
import java.util.Set;

public class LiteralEQ implements Literal {
	public String term_left_, term_right_;

	public LiteralEQ(String term_left , String term_right) {
		term_left_ = term_left;
		term_right_ = term_right;
	}

	@Override
	public Set<String> get_attr() {
		// TODO Auto-generated method stub
		return Collections.emptySet();
	}
}