package db.prob.datalog.query.Absyn; // Java Package generated by the BNF Converter.

import db.prob.datalog.query.Visitable;
import db.prob.datalog.query.Visitor;

public class PredicateSym  implements Visitable
{
  public String string_;

  public PredicateSym(String p1) { string_ = p1; }

  public void accept(Visitor v) { v.visit(this); }
}

